/*
 * music.h
 *
 *  Created on: 22 déc. 2021
 *      Author: Cedric
 */

#ifndef MODULE_SOUND_MUSIC_H_
#define MODULE_SOUND_MUSIC_H_

#include <stdint.h>
#include "sound.h"
/*
note_t g_tSong[32]=
{
        {DO, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {FA, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {FA, CROCHE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {FA, CROCHE},
        {PAUSE, NOIRE},
        {DO, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {RE, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {RE, CROCHE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {RE, CROCHE},
        {PAUSE, NOIRE},
        {DO, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {MI, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {MI, CROCHE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {MI, CROCHE},
        {PAUSE, NOIRE},
        {DO, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {FA, NOIRE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {FA, CROCHE},
        {PAUSE, STYLE_TRIPLE_CROCHE},
        {FA, CROCHE},
        {STOP, NOIRE}
};



note_t g_ptPapaNoel[] =
{
 {DO_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {FA_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {SOL_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {FA_FREQUENCY_3, BLANCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {SOL_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {LA_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {LA_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {LA_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {SIb_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {LA_FREQUENCY_3, BLANCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {SOL_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {FA_FREQUENCY_3, NOIRE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {MI_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {RE_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {DO_FREQUENCY_3, BLANCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {DO_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {DO_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {FA_FREQUENCY_3, BLANCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {FA_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {SOL_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},
 {SOL_FREQUENCY_3, CROCHE},
 {PAUSE, STYLE_TRIPLE_CROCHE},

 {FA_FREQUENCY_3, BLANCHE},
 {STOP, NOIRE}
};
*/

/*
//73BPM
note_t g_ptMonBeauSapin[] =
{
 {DO_FREQUENCY_3, STYLE_NOIRE, false},

 {FA_FREQUENCY_3, STYLE_CROCHE, true},
 {FA_FREQUENCY_3, STYLE_DOUBLE_CROCHE, false},
 {FA_FREQUENCY_3, STYLE_NOIRE, false},
 {SOL_FREQUENCY_3, STYLE_NOIRE, false},

 {LA_FREQUENCY_3, STYLE_CROCHE, true},
 {LA_FREQUENCY_3, STYLE_DOUBLE_CROCHE, false},
 {LA_FREQUENCY_3, STYLE_NOIRE, true},
 {LA_FREQUENCY_3, STYLE_CROCHE, false},

 {SOL_FREQUENCY_3, STYLE_CROCHE, false},
 {LA_FREQUENCY_3, STYLE_CROCHE, false},
 {SIb_FREQUENCY_3, STYLE_NOIRE, false},
 {MI_FREQUENCY_3, STYLE_NOIRE, false},

 {SOL_FREQUENCY_3, STYLE_NOIRE, false},
 {FA_FREQUENCY_3, STYLE_NOIRE, false},

 {NULL, NULL, NULL}
};
*/
note_t g_ptHappyBirthday[] =
{
     {DO_FREQUENCY_3, STYLE_CROCHE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_3, STYLE_CROCHE},

     {PAUSE, STYLE_TRIPLE_CROCHE},
     {RE_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {FA_FREQUENCY_3, STYLE_NOIRE},

     {PAUSE, STYLE_TRIPLE_CROCHE},
     {MI_FREQUENCY_3, STYLE_BLANCHE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_3, STYLE_CROCHE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_3, STYLE_CROCHE},

     {PAUSE, STYLE_TRIPLE_CROCHE},
     {RE_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {SOL_FREQUENCY_3, STYLE_NOIRE},


     {PAUSE, STYLE_TRIPLE_CROCHE},
     {FA_FREQUENCY_3, STYLE_BLANCHE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_3, STYLE_CROCHE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_3, STYLE_CROCHE},

     {PAUSE, STYLE_TRIPLE_CROCHE},
     {DO_FREQUENCY_4, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {LA_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {FA_FREQUENCY_3, STYLE_NOIRE},

     {PAUSE, STYLE_TRIPLE_CROCHE},
     {MI_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {RE_FREQUENCY_3, STYLE_BLANCHE},  //<-- A verifier
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {SIb_FREQUENCY_3, STYLE_CROCHE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {SIb_FREQUENCY_3, STYLE_CROCHE},

     {PAUSE, STYLE_TRIPLE_CROCHE},
     {LA_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {FA_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},
     {SOL_FREQUENCY_3, STYLE_NOIRE},
     {PAUSE, STYLE_TRIPLE_CROCHE},

     {FA_FREQUENCY_3, STYLE_NOIRE},
     {FA_FREQUENCY_3, STYLE_BLANCHE},

     {STOP, STYLE_NOIRE}
};




#endif /* MODULE_SOUND_MUSIC_H_ */
